stages:
  - build
  - test
  - sast
  - package
  - sca-package
  - sca-container
  - publish
  - deploy
  - dast
  - report


include:
  - local: 'todolist/.gitlab-ci.yml'
  - local: 'OWASP_JuiceShop/.gitlab-ci.yml'
  - local: 'ci/dashboard.gitlab-ci.yml'
  - local: 'ci/report-to-dashboard.gitlab-ci.yml'
